model_path : "results/cnn_bilstm_mltu1"
height : 64
width : 256 
batch_size : 64 
learning_rate : 0.002
train_epochs : 1000 
device : "mps" 


# new size (old was 32x128) 
# also new preprocess now filling with mean. 
